# [features]
# seeds = false
# [programs.localnet]
# solana_twitter = "Ff4hBJyVZVCdYCp1AQZ9FTAejSemT3NUM8XkdHtXvww7"

# [registry]
# url = "https://anchor.projectserum.com"

[programs.localnet]
solana_twitter = "Ff4hBJyVZVCdYCp1AQZ9FTAejSemT3NUM8XkdHtXvww7"

[programs.devnet]
solana_twitter = "Ff4hBJyVZVCdYCp1AQZ9FTAejSemT3NUM8XkdHtXvww7"

[programs.mainnet]
solana_twitter = "Ff4hBJyVZVCdYCp1AQZ9FTAejSemT3NUM8XkdHtXvww7"

[provider]
cluster = "devnet"
wallet = "/home/amir/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
